# Generated by Django 4.0.2 on 2022-02-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_manage', '0002_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
